"""Exchange connectivity — venue adapters with public/private clients."""

from mft.exchange.base import BaseClient, PrivateClient, PublicClient
from mft.exchange.errors import (
    ExchangeError,
    ExchangeNotConnectedError,
    InstrumentNotFoundError,
    InsufficientBalanceError,
    OrderError,
)
from mft.exchange.gate.spot import (
    GATE_SPOT_WS_URL,
    GateApiError,
    GateBalance,
    GateBookTicker,
    GateCandlestick,
    GateOrderAck,
    GateOrderBook,
    GateOrderBookUpdate,
    GateOrderUpdate,
    GateSpotWebSocket,
    GateTicker,
    GateTrade,
    GateUserTrade,
    GateWsError,
)
from mft.exchange.models import (
    Balance,
    BookLevel,
    Fill,
    Instrument,
    Order,
    OrderBook,
    OrderStatus,
    OrderType,
    PlaceOrderRequest,
    Side,
    Ticker,
    Trade,
)
from mft.exchange.oms import OmsView, Position
from mft.exchange.paper import (
    PaperAuthError,
    PaperExchange,
    PaperPrivateClient,
    PaperPublicClient,
)

__all__ = [
    "GATE_SPOT_WS_URL",
    "Balance",
    "BaseClient",
    "BookLevel",
    "ExchangeError",
    "ExchangeNotConnectedError",
    "Fill",
    "GateApiError",
    "GateBalance",
    "GateBookTicker",
    "GateCandlestick",
    "GateOrderAck",
    "GateOrderBook",
    "GateOrderBookUpdate",
    "GateOrderUpdate",
    "GateSpotWebSocket",
    "GateTicker",
    "GateTrade",
    "GateUserTrade",
    "GateWsError",
    "Instrument",
    "InstrumentNotFoundError",
    "InsufficientBalanceError",
    "Order",
    "OrderBook",
    "OrderError",
    "OrderStatus",
    "OrderType",
    "OmsView",
    "PaperAuthError",
    "PaperExchange",
    "PaperPrivateClient",
    "PaperPublicClient",
    "PlaceOrderRequest",
    "Position",
    "PrivateClient",
    "PublicClient",
    "Side",
    "Ticker",
    "Trade",
]
